import { Poppins, Quicksand } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "swiper/css";
import "@/assets/css/style.css";
import "@/assets/css/vendor/remixicon.css";
import AOSInit from "@/utils/AOSInit";
import PathProvider from "@/provider/PathProvider";
import Tooltips from "../utils/Tooltips";
import NextAuthSessionProvider from "@/provider/NextAuthSessionProvider";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Minnat Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${quicksand.variable}`}>
        <AOSInit />
        <Tooltips />
        <NextAuthSessionProvider>
          <PathProvider>
            <main className="wrapper sb-default">{children}</main>
          </PathProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
